### ISSUE TITLE
RandomMutator code and Error when save '_fullmodel.pt' in search stage.

### ISSUE THREAD

**Issue by Harvest-Li** [marsggbo/MICCAI2022-EMARS#1]
Hello, thank you very much for your great contribution!

In line 13 of the script MICCAI2022-EMARS/mutator/ea_mutator.py: "from .random_mutator import RandomMutator", could you provide the relevant code?

Also, during the search phase, I encountered the following error when trying to save the model:

```
Traceback (most recent call last):
File "search.py", line 60, in <module>
main(args)
File "search.py", line 42, in main
trainer.train(cfg.trainer.validate_always)
File "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/trainer/ea_trainer.py", line 162, in train
callback.on_epoch_end(epoch)
File "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/callbacks/callbacks.py", line 125, in on_epoch_end
self.save(epoch, is_last=True) # save last ckpt
File "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/callbacks/callbacks.py", line 164, in save
torch.save(model, dest_path.replace('.pth', '_fullmodel.pt'))
File "/home/liqs/anaconda3/envs/torch190/lib/python3.7/site-packages/torch/serialization.py", line 379, in save
_save(obj, opened_zipfile, pickle_module, pickle_protocol)
File "/home/liqs/anaconda3/envs/torch190/lib/python3.7/site-packages/torch/serialization.py", line 484, in _save
pickler.dump(obj)
File "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/utils/average_meter.py", line 28, in getattr
return self.meters[item]
KeyError: 'getstate'
```

Can you help me to fix it?

Thank you!

**Comment by marsggbo** [comment]
Hi @Harvest-Li , I just upload 'random_mutator.py'.

For the second issue, I think it is ok to comment on or remove the line "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/callbacks/callbacks.py", line 164,".

**Comment by Harvest-Li** [comment]
> Hi @Harvest-Li , I just upload 'random_mutator.py'.
> 
> For the second issue, I think it is ok to comment on or remove the line "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/callbacks/callbacks.py", line 164,".

Hi @marsggbo , thank you for your prompt reply! 
It's worth noting that in line 34 of the script MICCAI2022-EMARS/mutator/ea_mutator.py, perhaps it should be changed to `super().init(model, cfg)`

**Comment by Harvest-Li** [comment]
> Hi @Harvest-Li , I just upload 'random_mutator.py'.
> 
> For the second issue, I think it is ok to comment on or remove the line "/home/liqs/other_project/NAS/MICCAI2022-EMARS-main/callbacks/callbacks.py", line 164,".

Hi @marsggbo , thank you for your prompt reply!
It's worth noting that in line 34 of the script MICCAI2022-EMARS/mutator/ea_mutator.py, perhaps it should be changed to super().init(model)
